// Итальянские фразы и cloze для рабочего общения.

const IT_PHRASES = [
  // ===== Стендап и статусы =====
  { type: "phrase", it: "ieri ho lavorato sulla nuova funzionalità", ru: "вчера я работал над новой фичей", cat: "Стендап и статусы" },
  { type: "phrase", it: "oggi continuo con lo stesso compito", ru: "сегодня продолжу ту же задачу", cat: "Стендап и статусы" },
  { type: "phrase", it: "non ho blocchi", ru: "у меня нет блокеров", cat: "Стендап и статусы" },
  { type: "phrase", it: "sono bloccato dal team API", ru: "меня блокирует команда API", cat: "Стендап и статусы" },
  { type: "phrase", it: "ho bisogno di aiuto con questo compito", ru: "мне нужна помощь с этой задачей", cat: "Стендап и статусы" },
  { type: "phrase", it: "lo finirò entro domani", ru: "закончу к завтрашнему дню", cat: "Стендап и статусы" },
  { type: "phrase", it: "ho quasi finito", ru: "я почти закончил", cat: "Стендап и статусы" },
  { type: "phrase", it: "ci sto mettendo più del previsto", ru: "это занимает больше времени, чем ожидал", cat: "Стендап и статусы" },
  { type: "phrase", it: "ho avuto un problema con il database", ru: "я столкнулся с проблемой в базе данных", cat: "Стендап и статусы" },
  { type: "phrase", it: "ti tengo aggiornato", ru: "буду держать тебя в курсе", cat: "Стендап и статусы" },
  { type: "phrase", it: "vi faccio un breve aggiornamento", ru: "сделаю краткое обновление", cat: "Стендап и статусы" },
  { type: "phrase", it: "come ieri", ru: "как вчера", cat: "Стендап и статусы" },
  { type: "phrase", it: "ho appena completato la task", ru: "я только что завершил задачу", cat: "Стендап и статусы" },
  { type: "phrase", it: "sto lavorando al ticket numero 42", ru: "я работаю над тикетом 42", cat: "Стендап и статусы" },

  // ===== Встречи: ведение =====
  { type: "phrase", it: "iniziamo", ru: "давайте начнём", cat: "Встречи: ведение" },
  { type: "phrase", it: "grazie a tutti per essere qui", ru: "спасибо, что собрались", cat: "Встречи: ведение" },
  { type: "phrase", it: "condivido il mio schermo", ru: "сейчас покажу экран", cat: "Встречи: ведение" },
  { type: "phrase", it: "vedete il mio schermo?", ru: "вы видите мой экран?", cat: "Встречи: ведение" },
  { type: "phrase", it: "facciamo un giro di tavolo", ru: "давайте по кругу", cat: "Встречи: ведение" },
  { type: "phrase", it: "passiamo al prossimo punto", ru: "перейдём к следующему пункту", cat: "Встречи: ведение" },
  { type: "phrase", it: "ne riparliamo dopo", ru: "вернёмся к этому позже", cat: "Встречи: ведение" },
  { type: "phrase", it: "ne parliamo offline", ru: "обсудим это отдельно", cat: "Встречи: ведение" },
  { type: "phrase", it: "andiamo avanti", ru: "двигаемся дальше", cat: "Встречи: ведение" },
  { type: "phrase", it: "facciamo il punto", ru: "давайте сверим статус", cat: "Встречи: ведение" },
  { type: "phrase", it: "concludiamo", ru: "давайте заканчивать", cat: "Встречи: ведение" },
  { type: "phrase", it: "ci sono domande?", ru: "есть вопросы?", cat: "Встречи: ведение" },
  { type: "phrase", it: "ci sono dubbi?", ru: "есть какие-нибудь сомнения?", cat: "Встречи: ведение" },
  { type: "phrase", it: "vi mando il verbale dopo", ru: "разошлю протокол позже", cat: "Встречи: ведение" },
  { type: "phrase", it: "fissiamo un follow-up?", ru: "назначим повторную встречу?", cat: "Встречи: ведение" },
  { type: "phrase", it: "siamo in tempo?", ru: "мы укладываемся по времени?", cat: "Встречи: ведение" },

  // ===== Встречи: участие =====
  { type: "phrase", it: "scusami se ti interrompo", ru: "извини, что перебиваю", cat: "Встречи: участие" },
  { type: "phrase", it: "posso intervenire?", ru: "можно я вмешаюсь?", cat: "Встречи: участие" },
  { type: "phrase", it: "vorrei aggiungere una cosa", ru: "хочу кое-что добавить", cat: "Встречи: участие" },
  { type: "phrase", it: "riprendendo quello che ha detto Marco", ru: "развивая мысль Марко", cat: "Встречи: участие" },
  { type: "phrase", it: "ho una domanda", ru: "у меня вопрос", cat: "Встречи: участие" },
  { type: "phrase", it: "puoi chiarire?", ru: "не мог бы ты пояснить?", cat: "Встречи: участие" },
  { type: "phrase", it: "puoi spiegare meglio?", ru: "можешь объяснить лучше?", cat: "Встречи: участие" },
  { type: "phrase", it: "non ho capito bene", ru: "я не очень понял", cat: "Встречи: участие" },
  { type: "phrase", it: "puoi fare un esempio?", ru: "можешь привести пример?", cat: "Встречи: участие" },
  { type: "phrase", it: "puoi tornare alla slide precedente?", ru: "можешь вернуться к предыдущему слайду?", cat: "Встречи: участие" },
  { type: "phrase", it: "scusa, stai sparendo", ru: "извини, ты пропадаешь (связь)", cat: "Встречи: участие" },
  { type: "phrase", it: "credo che tu abbia il microfono spento", ru: "кажется, у тебя микрофон выключен", cat: "Встречи: участие" },
  { type: "phrase", it: "puoi parlare un po' più forte?", ru: "можешь говорить чуть громче?", cat: "Встречи: участие" },
  { type: "phrase", it: "è molto utile, grazie", ru: "это очень полезно, спасибо", cat: "Встречи: участие" },

  // ===== Согласие, несогласие =====
  { type: "phrase", it: "capisco cosa intendi", ru: "понимаю, что ты имеешь в виду", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "è un buon punto", ru: "это хорошее замечание", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "sono d'accordo", ru: "я согласен", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "non sono completamente d'accordo", ru: "я не совсем согласен", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "ho un'opinione diversa", ru: "у меня другое мнение", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "siamo sulla stessa lunghezza d'onda", ru: "мы на одной волне", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "correggimi se sbaglio", ru: "поправь меня, если я не прав", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "esatto, è proprio quello che pensavo", ru: "именно, я думал то же самое", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "puoi spiegarmi passo per passo?", ru: "можешь провести меня шаг за шагом?", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "ha senso", ru: "это имеет смысл", cat: "Согласие и обсуждение" },
  { type: "phrase", it: "non ha senso", ru: "это бессмыслица", cat: "Согласие и обсуждение" },

  // ===== Просьбы и запросы =====
  { type: "phrase", it: "puoi dare un'occhiata?", ru: "можешь взглянуть?", cat: "Просьбы и запросы" },
  { type: "phrase", it: "hai un minuto?", ru: "у тебя есть минута?", cat: "Просьбы и запросы" },
  { type: "phrase", it: "quando hai un attimo", ru: "когда будет минутка", cat: "Просьбы и запросы" },
  { type: "phrase", it: "puoi fare la review della mia PR?", ru: "можешь сделать ревью моего PR?", cat: "Просьбы и запросы" },
  { type: "phrase", it: "puoi spiegarmi il tuo codice?", ru: "можешь объяснить свой код?", cat: "Просьбы и запросы" },
  { type: "phrase", it: "mi aiuti a fare il debug?", ru: "поможешь с отладкой?", cat: "Просьбы и запросы" },
  { type: "phrase", it: "scrivimi quando è pronto", ru: "напиши, когда будет готово", cat: "Просьбы и запросы" },
  { type: "phrase", it: "puoi condividermi il documento?", ru: "можешь поделиться документом?", cat: "Просьбы и запросы" },
  { type: "phrase", it: "fammi sapere se va bene", ru: "дай знать, если подходит", cat: "Просьбы и запросы" },
  { type: "phrase", it: "ti va bene così?", ru: "тебе так подходит?", cat: "Просьбы и запросы" },
  { type: "phrase", it: "controllo e ti dico", ru: "проверю и сообщу", cat: "Просьбы и запросы" },
  { type: "phrase", it: "ci penso io", ru: "я этим займусь", cat: "Просьбы и запросы" },

  // ===== Дедлайны и планирование =====
  { type: "phrase", it: "qual è la scadenza?", ru: "какой дедлайн?", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "entro quando ti serve?", ru: "к когда тебе нужно?", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "dobbiamo spostare la scadenza", ru: "нам нужно сдвинуть дедлайн", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "possiamo prorogare la scadenza?", ru: "можем продлить срок?", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "sono in ritardo sulla tabella di marcia", ru: "я отстаю от графика", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "sono in linea con la tabella", ru: "иду по графику", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "siamo al limite con i tempi", ru: "мы впритык по срокам", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "fissiamo una scadenza precisa", ru: "поставим жёсткий дедлайн", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "lo finisco entro fine giornata", ru: "сделаю к концу дня", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "possiamo spostare la riunione a giovedì?", ru: "можем перенести встречу на четверг?", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "rimandiamo a domani", ru: "перенесём на завтра", cat: "Дедлайны и планирование" },
  { type: "phrase", it: "venerdì mattina ti va bene?", ru: "утро пятницы тебе подходит?", cat: "Дедлайны и планирование" },

  // ===== Код-ревью и фидбек =====
  { type: "phrase", it: "per me va bene", ru: "по мне выглядит хорошо", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "ho lasciato qualche commento", ru: "оставил несколько комментариев", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "puoi aggiungere dei test?", ru: "можешь добавить тесты?", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "questo va rifattorizzato", ru: "это нужно отрефакторить", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "dividiamolo in più PR", ru: "давай разобьём это на пулреквесты поменьше", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "credo ci sia un edge case", ru: "думаю, есть граничный случай", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "manca la gestione degli errori", ru: "не хватает обработки ошибок", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "puoi aggiungere un commento che spieghi il perché?", ru: "можешь добавить комментарий с объяснением?", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "approvo con commenti minori", ru: "аппрувлю с мелкими замечаниями", cat: "Код-ревью и фидбек" },
  { type: "phrase", it: "puoi ignorare se è fuori scope", ru: "можешь проигнорировать, если вне скоупа", cat: "Код-ревью и фидбек" },

  // ===== Проблемы и инциденты =====
  { type: "phrase", it: "la produzione è giù", ru: "продакшн лежит", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "abbiamo un incidente", ru: "у нас инцидент", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "sto investigando", ru: "я разбираюсь", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "faccio il rollback del deploy", ru: "откачу деплой", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "fammi riprodurre il problema", ru: "дай я воспроизведу проблему", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "non riesco a riprodurlo", ru: "у меня не получается воспроизвести", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "sul mio computer funziona", ru: "у меня на машине работает", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "abbiamo trovato la causa principale", ru: "мы нашли первопричину", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "è risolto", ru: "это решено", cat: "Проблемы и инциденты" },
  { type: "phrase", it: "facciamo un postmortem", ru: "проведём разбор инцидента", cat: "Проблемы и инциденты" },

  // ===== Самопрезентация и new joiner =====
  { type: "phrase", it: "mi chiamo Dmitry", ru: "меня зовут Дмитрий", cat: "Самопрезентация" },
  { type: "phrase", it: "vengo dalla Russia", ru: "я из России", cat: "Самопрезентация" },
  { type: "phrase", it: "lavoro come ingegnere software", ru: "я работаю инженером ПО", cat: "Самопрезентация" },
  { type: "phrase", it: "faccio parte del team di sviluppo", ru: "я в команде разработки", cat: "Самопрезентация" },
  { type: "phrase", it: "piacere di conoscervi", ru: "приятно с вами познакомиться", cat: "Самопрезентация" },
  { type: "phrase", it: "sto ancora imparando l'italiano", ru: "я ещё учу итальянский", cat: "Самопрезентация" },
  { type: "phrase", it: "potete parlare un po' più lentamente?", ru: "вы можете говорить чуть медленнее?", cat: "Самопрезентация" },

  // ===== Email фразы =====
  { type: "phrase", it: "ti scrivo per aggiornarti", ru: "пишу, чтобы тебя обновить", cat: "Email и переписка" },
  { type: "phrase", it: "come da accordi presi in riunione", ru: "согласно договорённости со встречи", cat: "Email и переписка" },
  { type: "phrase", it: "in allegato troverai il documento", ru: "во вложении найдёшь документ", cat: "Email и переписка" },
  { type: "phrase", it: "fammi sapere se ti serve altro", ru: "дай знать, если понадобится ещё что-то", cat: "Email и переписка" },
  { type: "phrase", it: "resto a disposizione per qualsiasi domanda", ru: "остаюсь на связи по любым вопросам", cat: "Email и переписка" },
  { type: "phrase", it: "in attesa di un tuo riscontro", ru: "жду твоего ответа", cat: "Email и переписка" },
  { type: "phrase", it: "scusa per il ritardo nella risposta", ru: "извини за поздний ответ", cat: "Email и переписка" },
  { type: "phrase", it: "grazie in anticipo", ru: "заранее благодарю", cat: "Email и переписка" },

  // ===== Small talk =====
  { type: "phrase", it: "come è andato il weekend?", ru: "как прошли выходные?", cat: "Small talk: фразы" },
  { type: "phrase", it: "hai fatto qualcosa di bello?", ru: "сделал что-нибудь интересное?", cat: "Small talk: фразы" },
  { type: "phrase", it: "come va la giornata?", ru: "как проходит день?", cat: "Small talk: фразы" },
  { type: "phrase", it: "tutto bene, grazie", ru: "всё хорошо, спасибо", cat: "Small talk: фразы" },
  { type: "phrase", it: "non c'è male", ru: "неплохо", cat: "Small talk: фразы" },
  { type: "phrase", it: "buon weekend!", ru: "хороших выходных!", cat: "Small talk: фразы" },
  { type: "phrase", it: "ci sentiamo presto", ru: "созвонимся / на связи", cat: "Small talk: фразы" },
  { type: "phrase", it: "piacere di conoscerti", ru: "приятно познакомиться", cat: "Small talk: фразы" },
  { type: "phrase", it: "andiamo a prendere un caffè?", ru: "пойдём за кофе?", cat: "Small talk: фразы" },
  { type: "phrase", it: "andiamo a pranzo?", ru: "пойдём обедать?", cat: "Small talk: фразы" },

  // ===== Cloze: фразы (пропуск слова) =====
  { type: "cloze", it: "in bocca ___ lupo", blank: "al", ru: "удачи (букв.: в пасть волку)", cat: "Cloze: фразы" },
  { type: "cloze", it: "fare il ___ della situazione", blank: "punto", ru: "сверить статус по ситуации", cat: "Cloze: фразы" },
  { type: "cloze", it: "stare con le mani in ___", blank: "mano", ru: "сидеть сложа руки", cat: "Cloze: фразы" },
  { type: "cloze", it: "rompere il ___", blank: "ghiaccio", ru: "сломать лёд", cat: "Cloze: фразы" },
  { type: "cloze", it: "siamo sulla stessa ___ d'onda", blank: "lunghezza", ru: "мы на одной волне", cat: "Cloze: фразы" },
  { type: "cloze", it: "ti tengo ___", blank: "aggiornato", ru: "буду держать тебя в курсе", cat: "Cloze: фразы" },
  { type: "cloze", it: "fammi ___ se va bene", blank: "sapere", ru: "дай знать, если ок", cat: "Cloze: фразы" },
  { type: "cloze", it: "non vedo ___ ora", blank: "l'", ru: "жду не дождусь", cat: "Cloze: фразы" },
  { type: "cloze", it: "tagliare la ___ al toro", blank: "testa", ru: "поставить точку в обсуждении", cat: "Cloze: фразы" },
  { type: "cloze", it: "essere al settimo ___", blank: "cielo", ru: "быть на седьмом небе", cat: "Cloze: фразы" },
  { type: "cloze", it: "in poche ___", blank: "parole", ru: "в двух словах", cat: "Cloze: фразы" },
  { type: "cloze", it: "alla ___ dei conti", blank: "fine", ru: "в конечном счёте", cat: "Cloze: фразы" },
  { type: "cloze", it: "tra l' ___", blank: "altro", ru: "между прочим", cat: "Cloze: фразы" },
  { type: "cloze", it: "secondo ___", blank: "me", ru: "по-моему", cat: "Cloze: фразы" },
  { type: "cloze", it: "a mio ___", blank: "parere", ru: "на мой взгляд", cat: "Cloze: фразы" },
  { type: "cloze", it: "a ___ proposito", blank: "tal", ru: "по этому поводу", cat: "Cloze: фразы" },
  { type: "cloze", it: "dare una ___", blank: "mano", ru: "помочь", cat: "Cloze: фразы" },
  { type: "cloze", it: "venire ___ contro", blank: "in", ru: "пойти навстречу", cat: "Cloze: фразы" },
  { type: "cloze", it: "fare un ___", blank: "favore", ru: "сделать одолжение", cat: "Cloze: фразы" },
  { type: "cloze", it: "dare un' ___", blank: "occhiata", ru: "взглянуть", cat: "Cloze: фразы" },
  { type: "cloze", it: "tenere ___ occhio", blank: "d'", ru: "присматривать за", cat: "Cloze: фразы" },
  { type: "cloze", it: "tenere a ___", blank: "mente", ru: "иметь в виду", cat: "Cloze: фразы" },
  { type: "cloze", it: "ci ___ io", blank: "penso", ru: "я этим займусь", cat: "Cloze: фразы" },
  { type: "cloze", it: "va ___", blank: "bene", ru: "хорошо / годится", cat: "Cloze: фразы" },
  { type: "cloze", it: "in ___ allegato", blank: "", ru: "во вложении", cat: "Cloze: фразы" },
  { type: "cloze", it: "cordiali ___", blank: "saluti", ru: "с уважением (в письме)", cat: "Cloze: фразы" },
  { type: "cloze", it: "a ___ presto", blank: "", ru: "до скорого", cat: "Cloze: фразы" },
  { type: "cloze", it: "non c'è ___", blank: "male", ru: "неплохо", cat: "Cloze: фразы" },
  { type: "cloze", it: "buona ___!", blank: "giornata", ru: "хорошего дня!", cat: "Cloze: фразы" },

  // ===== Cloze: предлоги и грамматика =====
  { type: "cloze", it: "vado ___ ufficio", blank: "in", ru: "иду в офис", cat: "Cloze: грамматика" },
  { type: "cloze", it: "vengo ___ Roma", blank: "da", ru: "я из Рима", cat: "Cloze: грамматика" },
  { type: "cloze", it: "una tazza ___ caffè", blank: "di", ru: "чашка кофе", cat: "Cloze: грамматика" },
  { type: "cloze", it: "lavoro ___ Milano", blank: "a", ru: "работаю в Милане", cat: "Cloze: грамматика" },
  { type: "cloze", it: "il libro è ___ tavolo", blank: "sul", ru: "книга на столе", cat: "Cloze: грамматика" },
  { type: "cloze", it: "vado al lavoro ___ macchina", blank: "in", ru: "еду на работу на машине", cat: "Cloze: грамматика" },
  { type: "cloze", it: "ci vediamo ___ lunedì", blank: "", ru: "увидимся в понедельник", cat: "Cloze: грамматика" },
  { type: "cloze", it: "abbiamo bisogno ___ aiuto", blank: "di", ru: "нам нужна помощь", cat: "Cloze: грамматика" },
  { type: "cloze", it: "questa è la mia ___", blank: "casa", ru: "это мой дом", cat: "Cloze: грамматика" },
  { type: "cloze", it: "che ore ___?", blank: "sono", ru: "сколько сейчас времени?", cat: "Cloze: грамматика" },
  { type: "cloze", it: "io ___ italiano", blank: "parlo", ru: "я говорю по-итальянски", cat: "Cloze: грамматика" },
];
