// Японские фразы и cloze для рабочего общения.
// Cloze: ja содержит ___, blank — пропущенное слово (на японском или romaji).

const JA_PHRASES = [
  // ===== Бизнес: приветствия и стандартные обороты =====
  { type: "phrase", ja: "お疲れ様です", kana: "おつかれさまです", romaji: "otsukaresama desu", ru: "стандартное приветствие коллеге (≈ «вы хорошо потрудились»)", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "本日もよろしくお願いします", kana: "ほんじつもよろしくおねがいします", romaji: "honjitsu mo yoroshiku onegaishimasu", ru: "сегодня тоже прошу вашего расположения", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "いつもお世話になっております", kana: "いつもおせわになっております", romaji: "itsumo osewa ni natte orimasu", ru: "благодарю за постоянное сотрудничество (открытие письма)", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "お忙しい中ありがとうございます", kana: "おいそがしいなかありがとうございます", romaji: "oisogashii naka arigatou gozaimasu", ru: "спасибо, что нашли время несмотря на занятость", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "申し訳ございません", kana: "もうしわけございません", romaji: "moushiwake gozaimasen", ru: "приношу глубочайшие извинения", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "ご迷惑をおかけしました", kana: "ごめいわくをおかけしました", romaji: "gomeiwaku o okake shimashita", ru: "извините за причинённое беспокойство", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "お手数をおかけしますが", kana: "おてすうをおかけしますが", romaji: "otesuu o okake shimasu ga", ru: "извините за хлопоты, но...", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "恐れ入りますが", kana: "おそれいりますが", romaji: "osoreirimasu ga", ru: "не сочтите за дерзость, но...", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "失礼いたします", kana: "しつれいいたします", romaji: "shitsurei itashimasu", ru: "извините за беспокойство (вежл., при входе)", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "お先に失礼します", kana: "おさきにしつれいします", romaji: "osaki ni shitsurei shimasu", ru: "извините, что ухожу раньше (стандарт при уходе с работы)", cat: "Бизнес: стандартные обороты" },
  { type: "phrase", ja: "今日はこの辺で失礼します", kana: "きょうはこのへんでしつれいします", romaji: "kyou wa kono hen de shitsurei shimasu", ru: "на сегодня я закончу", cat: "Бизнес: стандартные обороты" },

  // ===== Самопрезентация =====
  { type: "phrase", ja: "はじめまして", romaji: "hajimemashite", ru: "приятно познакомиться", cat: "Самопрезентация" },
  { type: "phrase", ja: "私はパンコフと申します", kana: "わたしはパンコフともうします", romaji: "watashi wa pankofu to moushimasu", ru: "меня зовут Панков", cat: "Самопрезентация" },
  { type: "phrase", ja: "ロシアから来ました", kana: "ロシアからきました", romaji: "roshia kara kimashita", ru: "я приехал из России", cat: "Самопрезентация" },
  { type: "phrase", ja: "エンジニアをしています", romaji: "enjinia o shite imasu", ru: "я работаю инженером", cat: "Самопрезентация" },
  { type: "phrase", ja: "開発チームに所属しています", kana: "かいはつチームにしょぞくしています", romaji: "kaihatsu chiimu ni shozoku shite imasu", ru: "я в команде разработки", cat: "Самопрезентация" },
  { type: "phrase", ja: "どうぞよろしくお願いします", kana: "どうぞよろしくおねがいします", romaji: "douzo yoroshiku onegaishimasu", ru: "прошу вашего расположения / приятно работать вместе", cat: "Самопрезентация" },
  { type: "phrase", ja: "日本語はまだ勉強中です", kana: "にほんごはまだべんきょうちゅうです", romaji: "nihongo wa mada benkyouchuu desu", ru: "я ещё учу японский", cat: "Самопрезентация" },
  { type: "phrase", ja: "ゆっくり話していただけますか", kana: "ゆっくりはなしていただけますか", romaji: "yukkuri hanashite itadakemasu ka", ru: "не могли бы вы говорить помедленнее?", cat: "Самопрезентация" },

  // ===== Стендап и статусы =====
  { type: "phrase", ja: "昨日の進捗を報告します", kana: "きのうのしんちょくをほうこくします", romaji: "kinou no shinchoku o houkoku shimasu", ru: "доложу о вчерашнем прогрессе", cat: "Стендап и статусы" },
  { type: "phrase", ja: "今日の予定を共有します", kana: "きょうのよていをきょうゆうします", romaji: "kyou no yotei o kyouyuu shimasu", ru: "поделюсь планами на сегодня", cat: "Стендап и статусы" },
  { type: "phrase", ja: "順調に進んでいます", kana: "じゅんちょうにすすんでいます", romaji: "junchou ni susunde imasu", ru: "продвигается по плану", cat: "Стендап и статусы" },
  { type: "phrase", ja: "予定通りです", kana: "よていどおりです", romaji: "yotei doori desu", ru: "идёт по плану", cat: "Стендап и статусы" },
  { type: "phrase", ja: "予定より遅れています", kana: "よていよりおくれています", romaji: "yotei yori okurete imasu", ru: "отстаём от плана", cat: "Стендап и статусы" },
  { type: "phrase", ja: "問題ありません", kana: "もんだいありません", romaji: "mondai arimasen", ru: "проблем нет / блокеров нет", cat: "Стендап и статусы" },
  { type: "phrase", ja: "今ブロッカーがあります", kana: "いまブロッカーがあります", romaji: "ima burokkaa ga arimasu", ru: "сейчас есть блокер", cat: "Стендап и статусы" },
  { type: "phrase", ja: "明日までに終わらせます", kana: "あしたまでにおわらせます", romaji: "ashita made ni owarasemasu", ru: "закончу к завтрашнему дню", cat: "Стендап и статусы" },
  { type: "phrase", ja: "もう少しで終わります", kana: "もうすこしでおわります", romaji: "mou sukoshi de owarimasu", ru: "почти закончил", cat: "Стендап и статусы" },
  { type: "phrase", ja: "想定より時間がかかっています", kana: "そうていよりじかんがかかっています", romaji: "soutei yori jikan ga kakatte imasu", ru: "занимает больше времени, чем ожидалось", cat: "Стендап и статусы" },
  { type: "phrase", ja: "サーバーで問題が発生しました", kana: "サーバーでもんだいがはっせいしました", romaji: "saabaa de mondai ga hassei shimashita", ru: "возникла проблема на сервере", cat: "Стендап и статусы" },

  // ===== Встречи: ведение и участие =====
  { type: "phrase", ja: "では、始めましょう", kana: "では、はじめましょう", romaji: "dewa, hajimemashou", ru: "тогда давайте начнём", cat: "Встречи" },
  { type: "phrase", ja: "今日のアジェンダです", kana: "きょうのアジェンダです", romaji: "kyou no ajenda desu", ru: "вот сегодняшняя повестка", cat: "Встречи" },
  { type: "phrase", ja: "画面を共有します", kana: "がめんをきょうゆうします", romaji: "gamen o kyouyuu shimasu", ru: "сейчас поделюсь экраном", cat: "Встречи" },
  { type: "phrase", ja: "画面が見えますか", kana: "がめんがみえますか", romaji: "gamen ga miemasu ka", ru: "вы видите мой экран?", cat: "Встречи" },
  { type: "phrase", ja: "声は聞こえていますか", kana: "こえはきこえていますか", romaji: "koe wa kikoete imasu ka", ru: "вы меня слышите?", cat: "Встречи" },
  { type: "phrase", ja: "音声が途切れています", kana: "おんせいがとぎれています", romaji: "onsei ga togirete imasu", ru: "звук прерывается", cat: "Встречи" },
  { type: "phrase", ja: "ミュートになっています", romaji: "myuuto ni natte imasu", ru: "у вас выключен микрофон", cat: "Встречи" },
  { type: "phrase", ja: "次の議題に移りましょう", kana: "つぎのぎだいにうつりましょう", romaji: "tsugi no gidai ni utsurimashou", ru: "перейдём к следующей теме", cat: "Встречи" },
  { type: "phrase", ja: "後ほど共有します", kana: "のちほどきょうゆうします", romaji: "nochihodo kyouyuu shimasu", ru: "поделюсь позднее", cat: "Встречи" },
  { type: "phrase", ja: "別途相談しましょう", kana: "べっとそうだんしましょう", romaji: "betto soudan shimashou", ru: "обсудим отдельно", cat: "Встречи" },
  { type: "phrase", ja: "そろそろ時間です", kana: "そろそろじかんです", romaji: "sorosoro jikan desu", ru: "уже подходит время", cat: "Встречи" },
  { type: "phrase", ja: "本日はこれで終わります", kana: "ほんじつはこれでおわります", romaji: "honjitsu wa kore de owarimasu", ru: "на сегодня закончим", cat: "Встречи" },
  { type: "phrase", ja: "議事録は後で共有します", kana: "ぎじろくはあとできょうゆうします", romaji: "gijiroku wa atode kyouyuu shimasu", ru: "протокол встречи поделюсь позже", cat: "Встречи" },
  { type: "phrase", ja: "ご質問はありますか", kana: "ごしつもんはありますか", romaji: "goshitsumon wa arimasu ka", ru: "есть ли у вас вопросы?", cat: "Встречи" },
  { type: "phrase", ja: "もう一度お願いします", kana: "もういちどおねがいします", romaji: "mou ichido onegaishimasu", ru: "повторите, пожалуйста", cat: "Встречи" },
  { type: "phrase", ja: "もう少し詳しく説明していただけますか", kana: "もうすこしくわしくせつめいしていただけますか", romaji: "mou sukoshi kuwashiku setsumei shite itadakemasu ka", ru: "не могли бы объяснить подробнее?", cat: "Встречи" },
  { type: "phrase", ja: "つまり、こういうことですか", romaji: "tsumari, kou iu koto desu ka", ru: "то есть это означает...?", cat: "Встречи" },

  // ===== Согласие, несогласие, обсуждение =====
  { type: "phrase", ja: "そうですね、賛成です", kana: "そうですね、さんせいです", romaji: "sou desu ne, sansei desu", ru: "верно, согласен", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "おっしゃる通りです", kana: "おっしゃるとおりです", romaji: "ossharu toori desu", ru: "именно так, как вы сказали", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "いい意見だと思います", kana: "いいいけんだとおもいます", romaji: "ii iken da to omoimasu", ru: "хорошее мнение", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "少し違う意見があります", kana: "すこしちがういけんがあります", romaji: "sukoshi chigau iken ga arimasu", ru: "у меня немного другое мнение", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "別の方法もあると思います", kana: "べつのほうほうもあるとおもいます", romaji: "betsu no houhou mo aru to omoimasu", ru: "думаю, есть и другой способ", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "それは難しいかもしれません", kana: "それはむずかしいかもしれません", romaji: "sore wa muzukashii kamoshiremasen", ru: "это, возможно, будет сложно", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "確認してから返答します", kana: "かくにんしてからへんとうします", romaji: "kakunin shite kara hentou shimasu", ru: "проверю и отвечу", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "持ち帰って検討します", kana: "もちかえってけんとうします", romaji: "mochikaette kentou shimasu", ru: "возьму с собой и подумаю", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "確かにその通りです", kana: "たしかにそのとおりです", romaji: "tashika ni sono toori desu", ru: "действительно, это так", cat: "Согласие и обсуждение" },
  { type: "phrase", ja: "申し訳ありませんが、それは難しいです", kana: "もうしわけありませんが、それはむずかしいです", romaji: "moushiwake arimasen ga, sore wa muzukashii desu", ru: "к сожалению, это сложно", cat: "Согласие и обсуждение" },

  // ===== Просьбы и запросы =====
  { type: "phrase", ja: "少しお時間よろしいですか", kana: "すこしおじかんよろしいですか", romaji: "sukoshi ojikan yoroshii desu ka", ru: "у вас есть минутка?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "確認していただけますか", kana: "かくにんしていただけますか", romaji: "kakunin shite itadakemasu ka", ru: "не могли бы проверить?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "レビューをお願いできますか", kana: "レビューをおねがいできますか", romaji: "rebyuu o onegai dekimasu ka", ru: "можете провести ревью?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "資料を送っていただけますか", kana: "しりょうをおくっていただけますか", romaji: "shiryou o okutte itadakemasu ka", ru: "не могли бы прислать материалы?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "教えていただけますか", kana: "おしえていただけますか", romaji: "oshiete itadakemasu ka", ru: "не могли бы объяснить?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "手伝っていただけますか", kana: "てつだっていただけますか", romaji: "tetsudatte itadakemasu ka", ru: "не могли бы помочь?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "アドバイスをいただけますか", romaji: "adobaisu o itadakemasu ka", ru: "можно ли получить совет?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "ご都合いかがですか", kana: "ごつごういかがですか", romaji: "gotsugou ikaga desu ka", ru: "как у вас со временем?", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "後ほどご連絡いたします", kana: "のちほどごれんらくいたします", romaji: "nochihodo gorenraku itashimasu", ru: "свяжусь с вами позже", cat: "Просьбы и запросы" },
  { type: "phrase", ja: "確認次第、ご連絡します", kana: "かくにんしだい、ごれんらくします", romaji: "kakunin shidai, gorenraku shimasu", ru: "как только проверю, свяжусь", cat: "Просьбы и запросы" },

  // ===== Дедлайны и планирование =====
  { type: "phrase", ja: "納期はいつですか", kana: "のうきはいつですか", romaji: "nouki wa itsu desu ka", ru: "какой дедлайн?", cat: "Дедлайны и планирование" },
  { type: "phrase", ja: "今週中にお願いします", kana: "こんしゅうちゅうにおねがいします", romaji: "konshuu chuu ni onegaishimasu", ru: "до конца недели, пожалуйста", cat: "Дедлайны и планирование" },
  { type: "phrase", ja: "金曜日までにできます", kana: "きんようびまでにできます", romaji: "kinyoubi made ni dekimasu", ru: "сделаю к пятнице", cat: "Дедлайны и планирование" },
  { type: "phrase", ja: "納期を延ばせますか", kana: "のうきをのばせますか", romaji: "nouki o nobasemasu ka", ru: "можно ли продлить срок?", cat: "Дедлайны и планирование" },
  { type: "phrase", ja: "間に合いそうにありません", kana: "まにあいそうにありません", romaji: "ma ni aisou ni arimasen", ru: "похоже, не успею", cat: "Дедлайны и планирование" },
  { type: "phrase", ja: "予定を変更したいのですが", kana: "よていをへんこうしたいのですが", romaji: "yotei o henkou shitai no desu ga", ru: "хотел бы изменить планы", cat: "Дедлайны и планирование" },
  { type: "phrase", ja: "会議を再調整しましょう", kana: "かいぎをさいちょうせいしましょう", romaji: "kaigi o saichousei shimashou", ru: "перенесём встречу", cat: "Дедлайны и планирование" },
  { type: "phrase", ja: "明日の午後はいかがですか", kana: "あしたのごごはいかがですか", romaji: "ashita no gogo wa ikaga desu ka", ru: "как насчёт завтрашнего дня (после обеда)?", cat: "Дедлайны и планирование" },

  // ===== Email и письменная коммуникация =====
  { type: "phrase", ja: "ご確認のほどよろしくお願いします", kana: "ごかくにんのほどよろしくおねがいします", romaji: "gokakunin no hodo yoroshiku onegaishimasu", ru: "прошу проверить (стандарт в письме)", cat: "Email и переписка" },
  { type: "phrase", ja: "添付ファイルをご確認ください", kana: "てんぷファイルをごかくにんください", romaji: "tenpu fairu o gokakunin kudasai", ru: "проверьте, пожалуйста, вложение", cat: "Email и переписка" },
  { type: "phrase", ja: "ご返信お待ちしております", kana: "ごへんしんおまちしております", romaji: "gohenshin omachi shite orimasu", ru: "буду ждать вашего ответа", cat: "Email и переписка" },
  { type: "phrase", ja: "ご不明な点がありましたらご連絡ください", kana: "ごふめいなてんがありましたらごれんらくください", romaji: "gofumei na ten ga arimashitara gorenraku kudasai", ru: "если будут вопросы, свяжитесь со мной", cat: "Email и переписка" },
  { type: "phrase", ja: "返信が遅くなり申し訳ありません", kana: "へんしんがおそくなりもうしわけありません", romaji: "henshin ga osoku nari moushiwake arimasen", ru: "извините за поздний ответ", cat: "Email и переписка" },
  { type: "phrase", ja: "ご了承ください", kana: "ごりょうしょうください", romaji: "goryoushou kudasai", ru: "прошу понимания (стандарт в письме)", cat: "Email и переписка" },
  { type: "phrase", ja: "下記の通りです", kana: "かきのとおりです", romaji: "kaki no toori desu", ru: "ниже изложено следующее", cat: "Email и переписка" },
  { type: "phrase", ja: "以上、よろしくお願いします", kana: "いじょう、よろしくおねがいします", romaji: "ijou, yoroshiku onegaishimasu", ru: "на этом всё, прошу содействия (стандарт. подпись)", cat: "Email и переписка" },

  // ===== Код-ревью и фидбек =====
  { type: "phrase", ja: "コードを確認しました", kana: "コードをかくにんしました", romaji: "koodo o kakunin shimashita", ru: "я просмотрел код", cat: "Код-ревью и фидбек" },
  { type: "phrase", ja: "問題なさそうです", kana: "もんだいなさそうです", romaji: "mondai nasasou desu", ru: "вроде проблем нет", cat: "Код-ревью и фидбек" },
  { type: "phrase", ja: "いくつかコメントを残しました", kana: "いくつかコメントをのこしました", romaji: "ikutsuka komento o nokoshimashita", ru: "оставил несколько комментариев", cat: "Код-ревью и фидбек" },
  { type: "phrase", ja: "テストを追加してください", kana: "テストをついかしてください", romaji: "tesuto o tsuika shite kudasai", ru: "добавьте, пожалуйста, тесты", cat: "Код-ревью и фидбек" },
  { type: "phrase", ja: "リファクタリングが必要です", kana: "リファクタリングがひつようです", romaji: "rifakutaringu ga hitsuyou desu", ru: "нужен рефакторинг", cat: "Код-ревью и фидбек" },
  { type: "phrase", ja: "PRを分けたほうがいいです", kana: "PRをわけたほうがいいです", romaji: "PR o waketa hou ga ii desu", ru: "лучше разбить пулреквест", cat: "Код-ревью и фидбек" },
  { type: "phrase", ja: "エッジケースを考慮してください", kana: "エッジケースをこうりょしてください", romaji: "ejji keesu o kouryo shite kudasai", ru: "учтите граничные случаи", cat: "Код-ревью и фидбек" },
  { type: "phrase", ja: "エラー処理が必要です", kana: "エラーしょりがひつようです", romaji: "eraa shori ga hitsuyou desu", ru: "нужна обработка ошибок", cat: "Код-ревью и фидбек" },

  // ===== Инциденты =====
  { type: "phrase", ja: "本番で障害が発生しました", kana: "ほんばんでしょうがいがはっせいしました", romaji: "honban de shougai ga hassei shimashita", ru: "произошёл сбой в продакшне", cat: "Проблемы и инциденты" },
  { type: "phrase", ja: "現在調査中です", kana: "げんざいちょうさちゅうです", romaji: "genzai chousachuu desu", ru: "сейчас расследуем", cat: "Проблемы и инциденты" },
  { type: "phrase", ja: "ロールバックします", romaji: "rooru bakku shimasu", ru: "сделаю откат", cat: "Проблемы и инциденты" },
  { type: "phrase", ja: "再現できません", kana: "さいげんできません", romaji: "saigen dekimasen", ru: "не могу воспроизвести", cat: "Проблемы и инциденты" },
  { type: "phrase", ja: "原因が分かりました", kana: "げんいんがわかりました", romaji: "gen'in ga wakarimashita", ru: "нашли причину", cat: "Проблемы и инциденты" },
  { type: "phrase", ja: "解決しました", kana: "かいけつしました", romaji: "kaiketsu shimashita", ru: "решено", cat: "Проблемы и инциденты" },
  { type: "phrase", ja: "ポストモーテムを行いましょう", kana: "ポストモーテムをおこないましょう", romaji: "posuto moutemu o okonaimashou", ru: "проведём разбор инцидента", cat: "Проблемы и инциденты" },

  // ===== Small talk =====
  { type: "phrase", ja: "週末はどう過ごしましたか", kana: "しゅうまつはどうすごしましたか", romaji: "shuumatsu wa dou sugoshimashita ka", ru: "как прошли выходные?", cat: "Small talk" },
  { type: "phrase", ja: "ゆっくり休めましたか", kana: "ゆっくりやすめましたか", romaji: "yukkuri yasumemashita ka", ru: "удалось отдохнуть?", cat: "Small talk" },
  { type: "phrase", ja: "週末の予定はありますか", kana: "しゅうまつのよていはありますか", romaji: "shuumatsu no yotei wa arimasu ka", ru: "есть планы на выходные?", cat: "Small talk" },
  { type: "phrase", ja: "今日は寒いですね", kana: "きょうはさむいですね", romaji: "kyou wa samui desu ne", ru: "сегодня холодно, не правда ли?", cat: "Small talk" },
  { type: "phrase", ja: "雨が降っていますね", kana: "あめがふっていますね", romaji: "ame ga futte imasu ne", ru: "идёт дождь", cat: "Small talk" },
  { type: "phrase", ja: "コーヒーでも飲みに行きませんか", kana: "コーヒーでものみにいきませんか", romaji: "koohii demo nomi ni ikimasen ka", ru: "не сходим за кофе?", cat: "Small talk" },
  { type: "phrase", ja: "ランチに行きましょう", kana: "ランチにいきましょう", romaji: "ranchi ni ikimashou", ru: "пойдёмте обедать", cat: "Small talk" },
  { type: "phrase", ja: "良い週末を", kana: "よいしゅうまつを", romaji: "yoi shuumatsu o", ru: "хороших выходных", cat: "Small talk" },
  { type: "phrase", ja: "また明日", kana: "またあした", romaji: "mata ashita", ru: "до завтра", cat: "Small talk" },

  // ===== Cloze: бизнес-фразы и частицы =====
  { type: "cloze", ja: "お疲れ___です", kana: "おつかれ___です", blank: "様", ru: "стандартное приветствие коллеге", cat: "Cloze: фразы" },
  { type: "cloze", ja: "よろしくお___します", kana: "よろしくお___します", blank: "願い", ru: "прошу вашего расположения", cat: "Cloze: фразы" },
  { type: "cloze", ja: "申し___ございません", kana: "もうし___ございません", blank: "訳", ru: "приношу глубочайшие извинения", cat: "Cloze: фразы" },
  { type: "cloze", ja: "お世話に___ております", kana: "おせわに___ております", blank: "なって", ru: "благодарю за сотрудничество", cat: "Cloze: фразы" },
  { type: "cloze", ja: "ご確認___ください", kana: "ごかくにん___ください", blank: "の上", ru: "просьба проверить (письмо)", cat: "Cloze: фразы" },
  { type: "cloze", ja: "ご連絡お___しております", kana: "ごれんらくお___しております", blank: "待ち", ru: "буду ждать вашего ответа", cat: "Cloze: фразы" },
  { type: "cloze", ja: "お先に___します", kana: "おさきに___します", blank: "失礼", ru: "ухожу раньше (стандарт при уходе с работы)", cat: "Cloze: фразы" },
  { type: "cloze", ja: "お疲れ様___した", kana: "おつかれさま___した", blank: "で", ru: "до свидания (после работы)", cat: "Cloze: фразы" },
  { type: "cloze", ja: "了解___ました", kana: "りょうかい___ました", blank: "し", ru: "принято / понял", cat: "Cloze: фразы" },
  { type: "cloze", ja: "承知___ました", kana: "しょうち___ました", blank: "し", ru: "понял (вежл.)", cat: "Cloze: фразы" },
  { type: "cloze", ja: "本日も___お願いします", kana: "ほんじつも___おねがいします", blank: "よろしく", ru: "сегодня тоже прошу", cat: "Cloze: фразы" },
  { type: "cloze", ja: "お手数___おかけしますが", kana: "おてすう___おかけしますが", blank: "を", ru: "извините за хлопоты", cat: "Cloze: фразы" },

  // ===== Cloze: частицы и грамматика =====
  { type: "cloze", ja: "私___学生です", kana: "わたし___がくせいです", blank: "は", ru: "я студент (тематическая частица «ва»)", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "鈴木さん___本を読みます", kana: "すずきさん___ほんをよみます", blank: "は", ru: "Судзуки-сан читает книгу", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "本___読みます", kana: "ほん___よみます", blank: "を", ru: "читаю книгу (объектная «о»)", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "学校___行きます", kana: "がっこう___いきます", blank: "に", ru: "иду в школу (направление)", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "公園___遊びます", kana: "こうえん___あそびます", blank: "で", ru: "играю в парке (место действия)", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "東京___来ました", kana: "とうきょう___きました", blank: "から", ru: "приехал из Токио", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "9時___5時まで", kana: "くじ___ごじまで", blank: "から", ru: "с 9 до 5", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "友達___映画を見ました", kana: "ともだち___えいがをみました", blank: "と", ru: "смотрел фильм с другом", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "私___本", kana: "わたし___ほん", blank: "の", ru: "моя книга (родительный)", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "これはペン___", romaji: "これはペン___", blank: "です", ru: "это ручка (связка-вежл.)", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "雨が___ています", kana: "あめが___ています", blank: "降っ", ru: "идёт дождь", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "今、何時___か", kana: "いま、なんじ___か", blank: "です", ru: "сколько сейчас времени?", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "もう一度お願い___ます", kana: "もういちどおねがい___ます", blank: "し", ru: "повторите, пожалуйста", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "明日会議が___ます", kana: "あしたかいぎが___ます", blank: "あり", ru: "завтра будет встреча", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "コーヒー___飲みますか", kana: "コーヒー___のみますか", blank: "を", ru: "будете кофе?", cat: "Cloze: грамматика" },
  { type: "cloze", ja: "8時___始まります", kana: "はちじ___はじまります", blank: "に", ru: "начнётся в 8", cat: "Cloze: грамматика" },
];
