// Готовые фразы и cloze-карточки для рабочего общения.
// Фразы: ru → en, целые предложения. Cloze: en с пропуском, ввести пропущенное слово.

const PHRASES = [
  // ===== Стендапы и статусы =====
  { type: "phrase", en: "Yesterday I worked on the new feature", ru: "Вчера я работал над новой фичей", cat: "Стендап и статусы" },
  { type: "phrase", en: "Today I'll continue with the same task", ru: "Сегодня я продолжу ту же задачу", cat: "Стендап и статусы" },
  { type: "phrase", en: "I have no blockers", ru: "У меня нет блокеров", cat: "Стендап и статусы" },
  { type: "phrase", en: "I'm blocked by the API team", ru: "Меня блокирует команда API", cat: "Стендап и статусы" },
  { type: "phrase", en: "I need help with this task", ru: "Мне нужна помощь с этой задачей", cat: "Стендап и статусы" },
  { type: "phrase", en: "I'll have it ready by tomorrow", ru: "Я закончу к завтрашнему дню", cat: "Стендап и статусы" },
  { type: "phrase", en: "I'm almost done", ru: "Я почти закончил", cat: "Стендап и статусы" },
  { type: "phrase", en: "It's taking longer than I expected", ru: "Это занимает больше времени, чем я ожидал", cat: "Стендап и статусы" },
  { type: "phrase", en: "I ran into an issue with the database", ru: "Я столкнулся с проблемой в базе данных", cat: "Стендап и статусы" },
  { type: "phrase", en: "I'll keep you posted", ru: "Я буду держать тебя в курсе", cat: "Стендап и статусы" },
  { type: "phrase", en: "Quick update on my progress", ru: "Краткое обновление по моему прогрессу", cat: "Стендап и статусы" },
  { type: "phrase", en: "Same as yesterday", ru: "Так же, как вчера", cat: "Стендап и статусы" },

  // ===== Встречи: открытие и ведение =====
  { type: "phrase", en: "Let's get started", ru: "Давайте начнём", cat: "Встречи: ведение" },
  { type: "phrase", en: "Thanks everyone for joining", ru: "Спасибо всем, что присоединились", cat: "Встречи: ведение" },
  { type: "phrase", en: "Let me share my screen", ru: "Давайте я покажу экран", cat: "Встречи: ведение" },
  { type: "phrase", en: "Can everyone see my screen?", ru: "Все видят мой экран?", cat: "Встречи: ведение" },
  { type: "phrase", en: "Let's go around the room", ru: "Давайте пройдёмся по кругу", cat: "Встречи: ведение" },
  { type: "phrase", en: "Let's move on to the next topic", ru: "Давайте перейдём к следующей теме", cat: "Встречи: ведение" },
  { type: "phrase", en: "Let's circle back to this later", ru: "Давайте вернёмся к этому позже", cat: "Встречи: ведение" },
  { type: "phrase", en: "Let's take this offline", ru: "Давайте обсудим это отдельно", cat: "Встречи: ведение" },
  { type: "phrase", en: "Let's wrap up", ru: "Давайте заканчивать", cat: "Встречи: ведение" },
  { type: "phrase", en: "Any questions before we finish?", ru: "Есть вопросы перед тем, как закончим?", cat: "Встречи: ведение" },
  { type: "phrase", en: "I'll send out the meeting notes", ru: "Я разошлю заметки со встречи", cat: "Встречи: ведение" },
  { type: "phrase", en: "Can we schedule a follow-up?", ru: "Можем назначить повторную встречу?", cat: "Встречи: ведение" },
  { type: "phrase", en: "Are we good on time?", ru: "Мы укладываемся по времени?", cat: "Встречи: ведение" },

  // ===== Встречи: участие, перебивания =====
  { type: "phrase", en: "Sorry to interrupt, but", ru: "Извините, что перебиваю, но", cat: "Встречи: участие" },
  { type: "phrase", en: "Can I jump in here?", ru: "Можно я вмешаюсь?", cat: "Встречи: участие" },
  { type: "phrase", en: "Just to add to that", ru: "Просто хочу добавить", cat: "Встречи: участие" },
  { type: "phrase", en: "Building on what John said", ru: "Развивая мысль Джона", cat: "Встречи: участие" },
  { type: "phrase", en: "I'd like to add something", ru: "Я хотел бы кое-что добавить", cat: "Встречи: участие" },
  { type: "phrase", en: "Could we go back to the previous slide?", ru: "Можем вернуться к предыдущему слайду?", cat: "Встречи: участие" },
  { type: "phrase", en: "Could you clarify what you mean?", ru: "Не могли бы вы пояснить, что вы имеете в виду?", cat: "Встречи: участие" },
  { type: "phrase", en: "I'm not sure I follow", ru: "Не уверен, что я понимаю", cat: "Встречи: участие" },
  { type: "phrase", en: "Could you give an example?", ru: "Не могли бы привести пример?", cat: "Встречи: участие" },
  { type: "phrase", en: "Sorry, you're breaking up", ru: "Извини, ты пропадаешь", cat: "Встречи: участие" },
  { type: "phrase", en: "I think you're on mute", ru: "Кажется, у тебя выключен микрофон", cat: "Встречи: участие" },
  { type: "phrase", en: "Could you speak up a bit?", ru: "Не могли бы говорить чуть громче?", cat: "Встречи: участие" },

  // ===== Согласие, несогласие, обсуждение =====
  { type: "phrase", en: "I see what you mean", ru: "Я понимаю, что ты имеешь в виду", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "That's a good point", ru: "Это хорошее замечание", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "I'd push back on that", ru: "Я бы поспорил с этим", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "I'm not sure I agree", ru: "Не уверен, что согласен", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "I have a different take", ru: "У меня другой взгляд на это", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "Let's agree to disagree", ru: "Давайте останемся каждый при своём мнении", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "I think we're on the same page", ru: "Думаю, мы на одной волне", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "Correct me if I'm wrong", ru: "Поправь меня, если я ошибаюсь", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "That's exactly what I was thinking", ru: "Это именно то, о чём я думал", cat: "Согласие и обсуждение" },
  { type: "phrase", en: "Could you walk me through it?", ru: "Не мог бы ты провести меня по этому шаг за шагом?", cat: "Согласие и обсуждение" },

  // ===== Запросы и просьбы =====
  { type: "phrase", en: "Could you take a look at this?", ru: "Не мог бы ты взглянуть на это?", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Do you have a minute?", ru: "У тебя есть минута?", cat: "Запросы и просьбы" },
  { type: "phrase", en: "When you have a chance", ru: "Когда у тебя будет возможность", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Could you review my pull request?", ru: "Не мог бы ты ревьюнуть мой пулреквест?", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Could you walk me through your code?", ru: "Не мог бы ты объяснить свой код?", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Would you mind helping me debug this?", ru: "Не мог бы ты помочь мне это отладить?", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Can you ping me when it's ready?", ru: "Можешь написать мне, когда будет готово?", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Could you share that document with me?", ru: "Не мог бы ты поделиться со мной этим документом?", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Let me know if that works for you", ru: "Дай знать, если тебе это подходит", cat: "Запросы и просьбы" },
  { type: "phrase", en: "Does that work for you?", ru: "Тебе это подходит?", cat: "Запросы и просьбы" },

  // ===== Дедлайны и планирование =====
  { type: "phrase", en: "What's the deadline?", ru: "Какой дедлайн?", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "When do you need it by?", ru: "К когда тебе это нужно?", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "We need to push the deadline back", ru: "Нам нужно сдвинуть дедлайн", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "Can we extend the deadline?", ru: "Можем ли мы продлить срок?", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "I'm running behind schedule", ru: "Я отстаю от графика", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "I'm on track to finish on time", ru: "Я успеваю в срок", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "We're cutting it close", ru: "Мы впритык по срокам", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "Let's set a hard deadline", ru: "Давайте поставим жёсткий дедлайн", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "I'll have it done by end of day", ru: "Я сделаю это к концу дня", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "Can we move the meeting to Thursday?", ru: "Можем перенести встречу на четверг?", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "Let's reschedule", ru: "Давайте перенесём", cat: "Дедлайны и планирование" },
  { type: "phrase", en: "Does Friday morning work for you?", ru: "Утро пятницы тебе подходит?", cat: "Дедлайны и планирование" },

  // ===== Ревью кода и фидбек =====
  { type: "phrase", en: "Looks good to me", ru: "По мне выглядит хорошо", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "I left a few comments", ru: "Я оставил несколько комментариев", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "Could you add some tests for this?", ru: "Не мог бы ты добавить тесты на это?", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "This needs a refactor", ru: "Это нужно отрефакторить", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "Let's split this into smaller PRs", ru: "Давайте разобьём это на пулреквесты поменьше", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "I think there's an edge case", ru: "Думаю, есть граничный случай", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "What about error handling?", ru: "А как насчёт обработки ошибок?", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "Could you add a comment explaining why?", ru: "Не мог бы ты добавить комментарий с объяснением?", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "Approving with minor comments", ru: "Аппрувлю с мелкими замечаниями", cat: "Код-ревью и фидбек" },
  { type: "phrase", en: "Feel free to ignore if it's out of scope", ru: "Можешь проигнорировать, если это вне скоупа", cat: "Код-ревью и фидбек" },

  // ===== Проблемы и инциденты =====
  { type: "phrase", en: "Production is down", ru: "Продакшн лежит", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "We have an incident", ru: "У нас инцидент", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "I'm investigating", ru: "Я разбираюсь", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "I'll roll back the deploy", ru: "Я откачу деплой", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "Let me reproduce the issue", ru: "Дай я воспроизведу проблему", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "I can't reproduce it on my end", ru: "У меня не получается воспроизвести", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "It works on my machine", ru: "У меня на машине работает", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "We found the root cause", ru: "Мы нашли первопричину", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "It's been resolved", ru: "Это решено", cat: "Проблемы и инциденты" },
  { type: "phrase", en: "Let's do a postmortem", ru: "Давайте проведём разбор инцидента", cat: "Проблемы и инциденты" },

  // ===== Small talk =====
  { type: "phrase", en: "How was your weekend?", ru: "Как прошли выходные?", cat: "Small talk: фразы" },
  { type: "phrase", en: "Anything fun planned?", ru: "Какие-нибудь интересные планы?", cat: "Small talk: фразы" },
  { type: "phrase", en: "How's your day going so far?", ru: "Как проходит твой день?", cat: "Small talk: фразы" },
  { type: "phrase", en: "I'm doing well, thanks", ru: "Всё хорошо, спасибо", cat: "Small talk: фразы" },
  { type: "phrase", en: "Hanging in there", ru: "Держусь", cat: "Small talk: фразы" },
  { type: "phrase", en: "Can't complain", ru: "Не жалуюсь", cat: "Small talk: фразы" },
  { type: "phrase", en: "Have a great weekend", ru: "Отличных выходных", cat: "Small talk: фразы" },
  { type: "phrase", en: "Talk to you soon", ru: "До связи", cat: "Small talk: фразы" },
  { type: "phrase", en: "Nice meeting you", ru: "Приятно было познакомиться", cat: "Small talk: фразы" },
  { type: "phrase", en: "Where are you joining from today?", ru: "Откуда ты сегодня подключаешься?", cat: "Small talk: фразы" },

  // ===== Cloze (пропуск слова) =====
  { type: "cloze", en: "Let's take this ___", blank: "offline", ru: "Давайте обсудим это отдельно", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's circle ___ to this later", blank: "back", ru: "Давайте вернёмся к этому позже", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'll keep you ___", blank: "posted", ru: "Я буду держать тебя в курсе", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let me know if it ___ for you", blank: "works", ru: "Дай знать, если тебе это подходит", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'm running ___ time", blank: "out of", ru: "У меня заканчивается время", cat: "Cloze: фразы" },
  { type: "cloze", en: "We're on the same ___", blank: "page", ru: "Мы на одной волне", cat: "Cloze: фразы" },
  { type: "cloze", en: "That makes ___", blank: "sense", ru: "Это имеет смысл", cat: "Cloze: фразы" },
  { type: "cloze", en: "Could you walk me ___ it?", blank: "through", ru: "Не мог бы ты провести меня по этому?", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'll get back to you ___", blank: "shortly", ru: "Я вернусь к тебе вскоре", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's ___ this up", blank: "wrap", ru: "Давайте заканчивать", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's ___ it off", blank: "kick", ru: "Давайте начнём (kick off)", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'll look ___ it", blank: "into", ru: "Я разберусь", cat: "Cloze: фразы" },
  { type: "cloze", en: "Could you follow ___ on that?", blank: "up", ru: "Не мог бы ты вернуться к этому?", cat: "Cloze: фразы" },
  { type: "cloze", en: "That's a fair ___", blank: "point", ru: "Это справедливое замечание", cat: "Cloze: фразы" },
  { type: "cloze", en: "Off the ___ of my head", blank: "top", ru: "Навскидку", cat: "Cloze: фразы" },
  { type: "cloze", en: "At the end of the ___", blank: "day", ru: "В конечном счёте", cat: "Cloze: фразы" },
  { type: "cloze", en: "Long story ___", blank: "short", ru: "Короче говоря", cat: "Cloze: фразы" },
  { type: "cloze", en: "Sorry to ___ in", blank: "jump", ru: "Извини, что вмешиваюсь", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'd like to ___ a question", blank: "ask", ru: "Я хотел бы задать вопрос", cat: "Cloze: фразы" },
  { type: "cloze", en: "Could you ___ that?", blank: "repeat", ru: "Не могли бы вы повторить?", cat: "Cloze: фразы" },
  { type: "cloze", en: "I didn't ___ that", blank: "catch", ru: "Я не расслышал", cat: "Cloze: фразы" },
  { type: "cloze", en: "You're on ___", blank: "mute", ru: "У тебя выключен микрофон", cat: "Cloze: фразы" },
  { type: "cloze", en: "Could you share your ___?", blank: "screen", ru: "Не мог бы ты поделиться экраном?", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let me know if you have any ___", blank: "questions", ru: "Дайте знать, если есть вопросы", cat: "Cloze: фразы" },
  { type: "cloze", en: "Feel free to ___ out", blank: "reach", ru: "Не стесняйтесь обращаться", cat: "Cloze: фразы" },
  { type: "cloze", en: "Looking forward to ___ from you", blank: "hearing", ru: "Жду вашего ответа", cat: "Cloze: фразы" },
  { type: "cloze", en: "Please find ___", blank: "attached", ru: "Во вложении", cat: "Cloze: фразы" },
  { type: "cloze", en: "As ___ in our last meeting", blank: "discussed", ru: "Как обсуждали на прошлой встрече", cat: "Cloze: фразы" },
  { type: "cloze", en: "I wanted to ___ up on this", blank: "follow", ru: "Я хотел уточнить статус", cat: "Cloze: фразы" },
  { type: "cloze", en: "Apologies for the ___ reply", blank: "late", ru: "Извините за поздний ответ", cat: "Cloze: фразы" },
  { type: "cloze", en: "Can we ___ a follow-up?", blank: "schedule", ru: "Можем назначить повторную встречу?", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's ___ this", blank: "table", ru: "Давайте отложим это", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's ___ on", blank: "move", ru: "Давайте двигаться дальше", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'll ___ you a heads up", blank: "give", ru: "Я тебя предупрежу заранее", cat: "Cloze: фразы" },
  { type: "cloze", en: "Could you ___ me in the loop?", blank: "keep", ru: "Можешь держать меня в курсе?", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let me ___ back to you", blank: "get", ru: "Я вернусь к тебе позже", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'm ___ behind schedule", blank: "running", ru: "Я отстаю от графика", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'm ___ track to finish on time", blank: "on", ru: "Я успеваю в срок", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'll ___ care of it", blank: "take", ru: "Я этим займусь", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's ___ it a try", blank: "give", ru: "Давайте попробуем", cat: "Cloze: фразы" },
  { type: "cloze", en: "We need to ___ the bar", blank: "raise", ru: "Нам нужно поднять планку", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's not ___ corners", blank: "cut", ru: "Давайте не будем халтурить", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's go the extra ___", blank: "mile", ru: "Давайте приложим дополнительные усилия", cat: "Cloze: фразы" },
  { type: "cloze", en: "Keep an ___ on the metrics", blank: "eye", ru: "Присматривай за метриками", cat: "Cloze: фразы" },
  { type: "cloze", en: "Bear in ___ the deadline", blank: "mind", ru: "Имей в виду дедлайн", cat: "Cloze: фразы" },
  { type: "cloze", en: "Take it into ___", blank: "account", ru: "Принимай это во внимание", cat: "Cloze: фразы" },
  { type: "cloze", en: "I'll ___ it out", blank: "figure", ru: "Я разберусь", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let me ___ that up", blank: "look", ru: "Дай-ка я это поищу", cat: "Cloze: фразы" },
  { type: "cloze", en: "Could you ___ this email to John?", blank: "forward", ru: "Не мог бы ты переслать это письмо Джону?", cat: "Cloze: фразы" },
  { type: "cloze", en: "Let's ___ a meeting for tomorrow", blank: "set up", ru: "Давайте назначим встречу на завтра", cat: "Cloze: фразы" },
];
